# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift

podfile: Example/Podfile

before_install:
  - which swiftlint || brew install swiftlint
  - gem install cocoapods

osx_image:
  - xcode8

matrix:
    include:
        # Swift 3.0
        - os: osx
          osx_image: xcode8
          env: 
            - TASK=lintpod
              SWIFT_VERSION=3.0
        - os: osx
          osx_image: xcode8
          env: 
            - TASK=carthage
              SWIFT_VERSION=3.0

script:
  - rake ci:$TASK
